services:
  # Layanan Backend kamu (SijaHub)
  sijahub-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kelompok7-sijahub
    # Kita pakai expose (jalur internal), jadi port 5000 gak bocor ke luar
    expose:
      - "5000"
    env_file:
      - ./backend/.env
    restart: always

  # Layanan Nginx (Pintu Depan/Proxy)
  nginx-proxy:
    image: nginx:alpine
    container_name: kelompok7-nginx
    ports:
      - "80:80"  # Akses lewat browser cukup pake IP/Domain aja
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - sijahub-app
    restart: always