server {
    # Nginx dengerin di port 80 (internal docker)
    listen 80;
    server_name comneta4.tailc90b09.ts.net;

    # 1. BAGIAN FRONTEND (Agar langsung muncul webnya)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # 2. BAGIAN BACKEND (Oper bola ke Node.js)
    location /api/ {
        proxy_pass http://sijahub-app:5000; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}