server {
    listen 80;
    server_name comneta4.tailc90b09.ts.net;

    root /usr/share/nginx/html;
    index pages/index.html;

    location / {
        # URUTAN CARI YANG PALING BENAR:
        # 1. Cari file asli (untuk CSS/JS/Assets)
        # 2. Cari file .html di dalam folder /pages/
        # 3. Cari folder /pages/namafile/
        # 4. Kalau mentok, balik ke index.html di dalam pages
        try_files $uri $uri/ /pages/$uri /pages/$uri.html /pages/index.html =404;
    }

    # JALUR DATA BACKEND (API)
    location /api/ {
        proxy_pass http://sijahub-app:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}