server {
    listen 80;
    server_name comneta4.tailc90b09.ts.net;

    # Kita buka folder utama frontend
    root /usr/share/nginx/html;
    index pages/index.html;

    location / {
        # 1. Cari file sesuai nama (misal: /css/style.css atau /assets/logo.png)
        # 2. Kalau gak ketemu, cari di dalam folder pages (misal: /view_daftarsiswa.html)
        # 3. Kalau masih gak ada, baru balik ke Beranda (index.html)
        try_files $uri $uri/ /pages$uri /pages$uri.html /pages/index.html =404;
    }

    # Jalur API ke Backend tetep harus ada ya biar datanya muncul
    location /api/ {
        proxy_pass http://sijahub-app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}